[features]
seeds = false
skip-lint = false
[programs.localnet]
demo_pda = "9yQ5rLuamV6voCNZcx7NGUBAT3EXxJvpeGVXZ1MbM9vQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/ausinmoothart/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
